version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=example
        - MYSQL_DATABASE=sc
        - MYSQL_USER=sc
        - MYSQL_PASSWORD=sc
    ports:
        - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
      build:
          context: .
          dockerfile: Dockerfile.yml
      ports:
          - 8000:8000
      links:
          - db
      environment:
          - MYSQL_ROOT_PASSWORD=example
          - MYSQL_DATABASE=sc
          - MYSQL_USER=sc
          - MYSQL_PASSWORD=sc
      volumes:
          - .:/var/www/html
      entrypoint: ./entrypoint.sh
volumes:
  mysql-data:
